### teste de erro
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "seuemail@teste.com",
  "password": "suasenha"
}

### teste de acerto
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "admin@hotmail.com",
  "password": "admin123"
}
### end login


### begin teste token
### value token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGhvdG1haWwuY29tIiwiZXhwIjoxNzUxMDgwMjEwfQ.hpbT48WMsvZecD0QfBggXHdcw2_B1vmSf4eVlN8DOy8
### token errado
GET http://localhost:3000/verifyToken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
### Testar certo
GET http://localhost:3000/verifyToken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGhvdG1haWwuY29tIiwiZXhwIjoxNzUxMDgwNjM2fQ.Cu9ZAQvO2n3sSOb0G98hZbvk7vkStNDP8sGDM3GWtlQ


###
